### PR TITLE
adding macos and linux evergreen links for sqlpackage

### PR DESCRIPTION
**Pull request by dzsquared**

### CODE REVIEW

**Comment by dzsquared** [comment]
There's a similar "sqlpackage-windows" link for the .NET Core Windows version or "dacfx-msi" for the MSI, if there's interest in also directing the Windows install to the latest version perpetually.
@potatoqualitee

**Comment by potatoqualitee** [comment]
Sweet as heck, thank you for this PR! The latest update for Windows sounds good. Looks like chocolatey is used to install sqlpackage currently and it takes a while on Windows -- 1.5 minutes. 

Perhaps we can use the Microsoft downloads and download/install both Full and Core if the timing looks good? Or should we do sqlpckage-core?

**Comment by potatoqualitee** [comment]
some big changes were made recently, please update your branch at your convenience 🙇🏼

**Comment by dzsquared** [comment]
@potatoqualitee I wanted to check your thoughts on whether sqlpackage should skip install on Linux/Windows as it's already present on the provided runners.  The "sqlclient" option for mssql-tools follows this pattern and only installs for macos.

**Comment by potatoqualitee** [comment]
@dzsquared -- i'd considered that and forgot why i didnt skip. probably because of sunk time costs. Happy to accept this PR with the skip!

**Comment by potatoqualitee** [comment]
I will merge this as @lowlydba is about to do some link updates, thank you! 🙇🏼

**Pull request merged**
